# Generated by Django 4.2.20 on 2025-04-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_address', models.TextField()),
                ('shop_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('shop_type', models.CharField(choices=[('grocery', 'Grocery'), ('electronics', 'Electronics'), ('clothing', 'Clothing')], max_length=50)),
                ('shop_status', models.CharField(choices=[('active', 'Open'), ('inactive', 'Close')], max_length=20)),
                ('shop_condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=20)),
                ('shop_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('password', models.CharField(max_length=128)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
