# Generated by Django 4.2.20 on 2025-04-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_address', models.TextField()),
                ('shop_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('shop_type', models.CharField(choices=[('grocery', 'Grocery'), ('electronics', 'Electronics'), ('clothing', 'Clothing')], max_length=50)),
                ('shop_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
