# Generated by Django 4.2.20 on 2025-04-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
