# Generated by Django 4.2.20 on 2025-05-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_shop_shop_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop_rating',
        ),
        migrations.CreateModel(
            name='Review_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.users_table')),
            ],
        ),
        migrations.CreateModel(
            name='Product_table',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_quantity', models.IntegerField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Category_table',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.shop')),
            ],
        ),
    ]
